version: "3.3"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,sns,sqs
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localhost:8000"
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - localstack

  producer:
    image: ghcr.io/justdice/devopstest-producer:latest
    environment:
      CLOUD_AWS_DEFAULTS_ENDPOINT: "http://localhost:4566"
    depends_on:
      - localstack

  consumer:
    image: ghcr.io/justdice/devopstest-consumer:latest
    environment:
      CLOUD_AWS_DEFAULTS_ENDPOINT: "http://localhost:4566"
    depends_on:
      - localstack